### ISSUE TITLE
Can't even start Strapi after installing plugin

### ISSUE THREAD

**Issue by feojoker** [webvibe-io/strapi-plugin-instagram#11]
STRAPI VERSION v4.4.1
NODE VERSION v16.18.1

After installing plugin got error on compilation `Could not load js config file ~/node_modules/@webvibe-io/strapi-plugin-instagram/strapi-server.js: Cannot find module './instagramBasicApi'`

Official docs telling, that Configuration should be done inside Strapi at Settings menu.

What am I doing wrong?

**Comment by SvenWesterlaken** [comment]
Got the same problem when running on my production server:

Strapi Version: 4.6
Node Version: 19.5

**Comment by joaoMarvelous** [comment]
Same problem here with the following versions :
STRAPI VERSION v4.5.3 (v4.6.0 aswell)
NODE VERSION v16.15.1

Locally, everything works fine but it doesn't in production environment.

**Comment by kepes** [comment]
Yes, you don't need to configure anything in CLI. Strapi 4.5.3 and Node 16.15.1 should be fine I'm using the same setup in production. Maybe your environment variables configure different node version. Can you copy the output of starting strapi where we can check versions? `package.json` also may help to figure out what is you problem. Full error message also would be helpful.

**Comment by kepes** [comment]
I figured out there were some camel case issue. I fixed it in [version 1.2.3](https://github.com/webvibe-io/strapi-plugin-instagram/releases/tag/v1.2.3) just upgrade package with `npm upgrade @webvibe-io/strapi-plugin-instagram`
