### ISSUE TITLE
Error during downloading images

### ISSUE THREAD

**Issue by ozireh** [webvibe-io/strapi-plugin-instagram#17]
After successfully generating all my tokens, I encountered an error during images download, that produced the following error message:

```
[2023-02-14 10:47:42.260] error: insert into "instagram_images" ("created_at", "instagram_id", "original_url", "published_at", "timestamp", "updated_at") values ($1, $2, $3, $4, $5, $6) returning "id" - value too long for type character varying(255)
error: insert into "instagram_images" ("created_at", "instagram_id", "original_url", "published_at", "timestamp", "updated_at") values ($1, $2, $3, $4, $5, $6) returning "id" - value too long for type character varying(255)
```

It appears that the current format of the "original_url" field does not allow for enough characters.

Pull Request: #16

**Comment by kepes** [comment]
Thanks for your pull request I will merge it to the master. Could you send me such a URL just for my curiosity please?

**Comment by ozireh** [comment]
Here is an example of the type of URL we receive:
https://scontent-zrh1-1.cdninstagram.com/v/t51.2885-15/313962548_604349168108804_9137547227584862586_n.jpg?stp=dst-jpg_e35&_nc_ht=scontent-zrh1-1.cdninstagram.com&_nc_cat=108&_nc_ohc=sa0QN_0pNKYAX_6zY9a&edm=ABmJApABAAAA&ccb=7-5&ig_cache_key=Mjk2MTk5OTUwODc0NTkwMTcyNw%3D%3D.2-ccb7-5&oh=00_AfDgeo8XNvPWHK-qNfs8P0Uy9g8rL9GxWUaXApK4rlbtxQ&oe=63F11695&_nc_sid=6136e7

**Comment by SvenWesterlaken** [comment]
Unfortunately, got the same error. Think the pull request should be sufficient to fix it.

**Comment by kepes** [comment]
New version [1.2.4](https://github.com/webvibe-io/strapi-plugin-instagram/releases/tag/v1.2.4) published. Maybe you need to regenerate DB for change field type (I don't know if Strapi notices the change)
