### ISSUE TITLE
Feature Request: option to post on Instagram

### ISSUE THREAD

**Issue by WardenCommander** [webvibe-io/strapi-plugin-instagram#6]
Add option to post images from strapi backend to insagram/Facebook page feed

**Comment by kepes** [comment]
I don't understand what is the point of this request. I think instagram has a very good app why do you need to post from Strapi to Instagram? I think you only need to change your workflow and post into Instagram first.

This request raises the following questions
- image sizes (resize, corp etc)
- filters (the app has very good filters)
- API only allow 25 image post per day

**Comment by WardenCommander** [comment]
I would like to automate posting, and have everything in one place, for example when you publish new blog/product you can post image to fb page and IG post, with strapi you can more easy repost same product and schedule posting.

**Comment by kepes** [comment]
I'm not planing to do this. I think this is beyond the scope of this project.
